### ISSUE TITLE
Function not implemented in Windows?

### ISSUE THREAD

**Issue by abc767234318** [bytecodealliance/wasm-micro-runtime#1298]
```
fn main() -> std::io::Result<()> {
	for entry in std::fs::read_dir("/")? {
		println!("{}", entry?.path().display());
	}
	Ok(())
}
```
This is a source code first mentioned in wasmtime issues NO.2618.

### Steps to Reproduce
```
rustup target add wasm32-wasi
cargo build --target wasm32-wasi
iwasm --dir=. demo.wasm
```
And I got the following error.
```
Error: Os { code: 52, kind: Unsupported, message: "Function not implemented" }
```
My test platform is Windows, but when I test on Ubuntu, I get no errors.

**Comment by abc767234318** [comment]
[demo.zip](https://githu@wenyongh .com/bytecodealliance/wasm-micro-runtime/files/9141131/demo.zip)
@wenyongh

**Comment by wenyongh** [comment]
@abc767234318 The issue is because that in Windows, we use uvwasi library to support the libc-wasi feature, and the uvwasi doesn't support `wasi_fd_readir` in Windows and Android:
https://github.com/nodejs/uvwasi/blob/main/src/uvwasi.c#L1417-L1418
https://github.com/nodejs/uvwasi/blob/main/src/uvwasi.c#L16-L18

Other runtime should also run failed in Windows if it uses uvwasi library. It is a little complex to fix `wasi_fd_read` by ourselves, we had better wait some time to see whether uvwasi will fix it. Thanks.

**Comment by abc767234318** [comment]
Thanks a lot !
