### ISSUE TITLE
[CI Optimization] Remove `check_repo` 

### ISSUE THREAD

**Issue by lum1n0us** [bytecodealliance/wasm-micro-runtime#1524]
Remove [`check_repo`](https://github.com/bytecodealliance/wasm-micro-runtime/blob/8436e88a0718af8614714bacfdff4cf45958def5/.github/workflows/compilation_on_android_ubuntu.yml#L65)  and its output and all related references.

- [ ] compilation_on_android_ubuntu.yml  
- [ ] compilation_on_macos.yml  
- [ ] compilation_on_nuttx.yml  
- [ ] compilation_on_sgx.yml  
- [ ] compilation_on_windows.yml

**Comment by TianlongLiang** [comment]
I removed it and found a way to disable jobs run on the forked repo by adding `if condition` for all jobs(but for testing purposes, comment it for now). I also made two jobs into independent reusable workflows, and so far, so good. But there is one thing worth noticing is that when passing the argument to called workflow, there are only three type are supported(string, number, boolean). Though there is a way to [walk around](https://github.com/community/community/discussions/11692) this problem and pass the type you want, it could become more tricky when input is complex

the current status can be seen in [this branch](https://github.com/TianlongLiang/wasm-micro-runtime/tree/reuseable_workflow )

**Comment by lum1n0us** [comment]
Second thought, maybe run workflows on foked repo is not a bad idea. Developers can use it as a verification environment and are able to prepare a high quality PR. So how about keeping enable jobs run on foked repos?

**Comment by lum1n0us** [comment]
`build_llvm.py --project clang lldb` is about to generate wamr-lldb binary. I guess we don't need it when building llvm libraries for *iwasm* and *wamrc*.

we can use another workflow, like * _build_wamr_lldb.yml* to handle wamr-lldb binary specificaly.

**Comment by lum1n0us** [comment]
> Second thought, maybe run workflows on foked repo is not a bad idea. Developers can use it as a verification environment and are able to prepare a high quality PR. So how about keeping enable jobs run on foked repos?

But we need to make sure run the release job only on *bytecodealliance/wasm-micro-runtime*.  Maybe ` if: ${{ github.repository_owner == 'bytecodealliance' }}`

**Comment by TianlongLiang** [comment]
> > Second thought, maybe run workflows on foked repo is not a bad idea. Developers can use it as a verification environment and are able to prepare a high quality PR. So how about keeping enable jobs run on foked repos?
> 
> But we need to make sure run the release job only on _bytecodealliance/wasm-micro-runtime_. Maybe ` if: ${{ github.repository_owner == 'bytecodealliance' }}`

Word. I also think about the situation where CI should be triggered on the forked branch, but maybe we could be limited them to less scenery. To think about it, all the commits on the BA branch will be from the pull request, right? Maybe we can only trigger the ci when the branch becomes a pull request base or a pull request target? In that way, CI doesn't have to be run every time sync fork or push a simple commit(if you want to test before PR, you can always trigger it manually). Theoretically, the code quality won't be hurt since we can specify the trigger condition so that CI will run on the base branch when PR is opened/edited and run on the target branch when merged if I understand the [document](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) correct. I will test whether this logic is feasible if you think this is a good practice

**Comment by lum1n0us** [comment]
IIUC, you are saying 
- remove the `on.push` trigger
- only run when a PR is opened, updated and closed with `push_request_target`

```
on:
  pull_request_target:
    types: [opened, synchronize, closed]

jobs:
   xxx:
  if: github.event.pull_request.merged == true
```

Sure, please take a look.

**Comment by lum1n0us** [comment]
https://github.com/bytecodealliance/wasm-micro-runtime/pull/1543
