### ISSUE TITLE
Unexpected `error_buf` population in `wasm_runtime_load`

### ISSUE THREAD

**Issue by csegarragonz** [bytecodealliance/wasm-micro-runtime#1705]
Hi,

I've realised that the method [`check_wasi_abi_compatibility`](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/interpreter/wasm_loader.c#L3837-L3946) of the interpreter's `wasm_loader` populates the error buffer even though no error took place. Admitttedly, the code succeeds to run (and the return code is zero), but I find this behaviour slightly counter-intuitive.

In particular, in the cited method (`check_wasi_abi_compatibility`), WAMR will look for either `_start` or `_initialize` (but not both). As a consequence, one of the lookups must fail. The failing lookup populates the error buffer with an error string. IMO the error string should be reset when checking that only one of the symbols was found, but wanted to ask if this is the expected behaviour.

**Comment by csegarragonz** [comment]
One of the checks in `check_wasi_abi_compatibility` is to check if the module exports _either_ `_start` or `_initialize` but _not_ both (exporting both would, correctly, yield an [error](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/interpreter/wasm_loader.c#L3915-L3922).

As a consequence either:
* The call to `wasm_loader_find_export` for `_start` ([here](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/interpreter/wasm_loader.c#L3869-L3870)), or
* the call to `wasm_loader_find_export` for `_initialize` ([here](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/interpreter/wasm_loader.c#L3883-L3884))
will fail, populating the error buffer.

Note that the call to `set_error_buf` happens _inside_ `wasm_loader_find_export` here: https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/core/iwasm/interpreter/wasm_loader.c#L711-L712

**Comment by lum1n0us** [comment]
I take your point now. It seems there is a possibility to overwrite the error message from `wasm_loader_find_export` in `check_wasi_abi_compatibility`. 

But it is allowed to be failed to look for `_start` or `_initialize`. In other words, the error message from 

https://github.com/bytecodealliance/wasm-micro-runtime/blob/021130f4a3377726d9b3ab595caf76214c55fa80/core/iwasm/interpreter/wasm_loader.c#L711-L712

will be ignored and/or be overwrite with a new one.

Another error message

https://github.com/bytecodealliance/wasm-micro-runtime/blob/021130f4a3377726d9b3ab595caf76214c55fa80/core/iwasm/interpreter/wasm_loader.c#L740

seems to be unnecessary because there is a validation in `load_export_section()`. We might remove it.

**Comment by lum1n0us** [comment]
#1720
