### ISSUE TITLE
Single debugging session for wasm application and embedder itself

### ISSUE THREAD

**Issue by eloparco** [bytecodealliance/wasm-micro-runtime#1744]
Hello,
I followed the guide [enable-debugging-in-embedders-for-interpreter](https://github.com/bytecodealliance/wasm-micro-runtime/blob/12bbb9189cfb0f9094f7f60d0b69ece48cd46a46/doc/source_debugging.md#enable-debugging-in-embedders-for-interpreter).

I have a Rust application that calls some native APIs registered by the embedder. I'm able to attach to the gdb server created by the embedder and debug my Rust code.
If I want to debug the interaction between the embedder and the WASM application, I start two debugging sessions: one for the embedder and, once the gdb server has started, I create another debugging session by attaching to the gdb server. Now, I put a breakpoint in the Rust code that calls the exported function (from the rust debugging session) and another breakpoint at the native exported function (from the embedder debugging session).

I was wondering if there is any way to combine the two debugging session into one and, once reached the call to the exported function in the WASM application, "step into" the embedder code that implements that function.

Hope my description was clear.
Thanks

**Comment by xujuntwt95329** [comment]
Currently this kind of feature is not supported in interpreter, the embedder code (native executable) and app code have different dwarf information, they are processed by two separate debuggers.

[Debugging with AoT](https://github.com/bytecodealliance/wasm-micro-runtime/blob/main/doc/source_debugging.md#debugging-with-aot) may support this kind of usage, because the debug information of app code is translated into native dwarf and both the native and app's dwarf information is processed by a single debugger, so you can navigate between native and app layer. However the AoT debugging support is not really available yet, it lacks many of common used features such as inspecting variables.
