### ISSUE TITLE
wasm_cluster_thread_waiting_run maybe blocked

### ISSUE THREAD

**Issue by qianyimao** [bytecodealliance/wasm-micro-runtime#1860]
Lock wait_lock before modifing “running_status” in wasm_cluster_thread_step.
if execution thread swapped out by os at “wasm_cluster_thread_waiting_run=>os_cond_wait=>os_cond_wait_internal line:569”. during this time gdbserver thread invoke wasm_cluster_thread_step or continue, cond will lose the notification.

**Comment by qianyimao** [comment]
@wenyongh

**Comment by xujuntwt95329** [comment]
Hi @qianyimao, thanks for reporting this issue.

Yes, by design, the `interpreter thread` and the `debugger thread` should not execute at the same time, so we don't do too much synchronization between them. The issue is because there is a very short time they do execute in parallel, which may cause the signal to be missed.

I'll fix the issue today or tomorrow. Thanks again!

**Comment by wenyongh** [comment]
@qianyimao We have submitted PR #1887 to fix this issue, could you help review and test it?
