### ISSUE TITLE
Question for wamr's support for C++ inheritance

### ISSUE THREAD

**Issue by takoyakiyo** [bytecodealliance/wasm-micro-runtime#314]
Can `wamr` support defining `C++` base class in native and exporting an interface, then defining derived class inherited the base class in `wasm app` for use? Similar to export native API to wasm application.

**Comment by xujuntwt95329** [comment]
I'm afraid not. 

The information of the base class is needed by the compiler. If you define the base class in native, how could your application be compiled since there is no information for the base class during the compiling time?

The `export native API` works because `function` is just a symbol during runtime, we can tell the compiler to `import` these functions from the runtime rather than resolve them during the linking time, but there is no mechanism for us to provide the information of a base class to the compiler.
