### ISSUE TITLE
Unexpected exception in JIT mode

### ISSUE THREAD

**Issue by erxiaozhou** [bytecodealliance/wasm-micro-runtime#3285]
### Subject of the issue
The WAMR on JIT mode raises an exception on a valid case.
### Test case

[i32.gt_s_54_485_17118920438119833.zip](https://github.com/bytecodealliance/wasm-micro-runtime/files/14896201/i32.gt_s_54_485_17118920438119833.zip)

### Your environment

* Host OS: Ubuntu 20.04
* Commit Id: 4ef724bbfffab1c7761b2674c483a8e7d7c840b8
### Steps to reproduce
1. build WAMR in JIT mode
```
export CC=/usr/lib/llvm-16/bin/clang
export CXX=/usr/lib/llvm-16/bin/clang++
cd product-mini/platforms/linux/;rm -rf build
cmake -DWAMR_BUILD_AOT=1 -DWAMR_BUILD_FAST_JIT=1   -DWAMR_BUILD_REF_TYPES=1 -DCMAKE_BUILD_TYPE=Release  -DWASM_ENABLE_BULK_MEMORY=1 -DWAMR_BUILD_LIBC_WASI=0 -DWAMR_BUILD_LIBC_BUILTIN=1 -DWAMR_BUILD_SIMD=1  -Bbuild
```
2. execute the command
```
iwasm --heap-size=0 --llvm-jit -f "to_test" <test_case>
```

### Expected behavior
return -1 or 4294967295

### Actual behavior
There is an exception
```
Exception: integer overflow
```

**Comment by wenyongh** [comment]
@erxiaozhou the issue was caused by failing to `table.grow` since by default WAMR sets the max table element size to 1024:
https://github.com/bytecodealliance/wasm-micro-runtime/blob/1c690b7561a99b8a7d3d91b7ec19a47c7e96074d/core/config.h#L586-L588

If we enlarge it to 20000, the case returns -1 as expected. We limited the maximum table element size due to in actual usage, it is mainly used for call_indirect opcode and in most cases 1024 is large enough. You can add `add_definitions(-DWASM_TABLE_MAX_SIZE=20000)` in the `CMakeLists.txt` to enlarge it. Thanks.

**Comment by lum1n0us** [comment]
https://github.com/bytecodealliance/wasm-micro-runtime/pull/3310
