### ISSUE TITLE
Complex native API 

### ISSUE THREAD

**Issue by CanYouGiveMeAName** [bytecodealliance/wasm-micro-runtime#405]
I add native function refer to export_native_api.md successfully. But my function is a little complex. If i put all these function in Enclave.cpp, it will be too long. I tried make another .cpp, then include it's .h. But not used. Please help. thx

**Comment by xujuntwt95329** [comment]
Hi,

I don't know what the compiler actually reported as you don't provide the error message, I guess there may be two possibilities:
1. Your functions are defined as static in the other .cpp file, so the linker can't find them.
2. You don't use `extern "C"` in your cpp file so the function name is mangling by the compiler, which cause the linking error.

If this is not the root cause, could you please provide your error message?

**Comment by CanYouGiveMeAName** [comment]
> Hi,
> 
> I don't know what the compiler actually reported as you don't provide the error message, I guess there may be two possibilities:
> 
> 1. Your functions are defined as static in the other .cpp file, so the linker can't find them.
> 2. You don't use `extern "C"` in your cpp file so the function name is mangling by the compiler, which cause the linking error.
> 
> If this is not the root cause, could you please provide your error message?

I will try. Thans very much.
